# Site settings
title: Transcend.py, your code one step closer to transcendence
tag_text: Transcend.py
description: Solo is a Jekyll theme that supports single-page websites only, but supports them well. Yes, it’s responsive.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
